#!/usr/bin/env python3
"""
Basic sanity checks for SO101Interface that don't require real hardware.

Run with:
    python3 test_so101_interface.py
    python3 -m unittest test_so101_interface -v
"""
import unittest

import numpy as np
import pinocchio as pin

from so101_interface import SO101Interface


class TestWithoutHardware(unittest.TestCase):
    """Interface behavior when no bus/hardware is connected (self.bus is None)."""

    def setUp(self):
        self.iface = SO101Interface()

    def test_starts_disconnected(self):
        self.assertFalse(self.iface.is_connected())
        self.assertFalse(self.iface.are_servos_enabled())

    def test_joint_reads_return_zeros(self):
        self.assertEqual(self.iface.get_joint_positions(), [0.0] * 5)
        self.assertEqual(self.iface.get_joint_velocities(), [0.0] * 5)

    def test_gripper_read_returns_none(self):
        self.assertIsNone(self.iface.get_gripper_position())

    def test_writes_fail_gracefully(self):
        self.assertFalse(self.iface.enable_servos())
        self.assertFalse(self.iface.set_joint_positions([0.0] * 5))
        self.assertFalse(self.iface.set_gripper_position(0.05))


class TestForwardKinematics(unittest.TestCase):
    def setUp(self):
        self.iface = SO101Interface()

    def test_get_eef_pose_is_valid_homogeneous_transform(self):
        T = self.iface.get_eef_pose()
        self.assertEqual(T.shape, (4, 4))

        # Bottom row must always be [0, 0, 0, 1]
        np.testing.assert_allclose(T[3, :], [0, 0, 0, 1], atol=1e-8)

        # Rotation block must be a valid rotation matrix (orthonormal, det=1)
        R = T[:3, :3]
        np.testing.assert_allclose(R @ R.T, np.eye(3), atol=1e-6)
        self.assertAlmostEqual(np.linalg.det(R), 1.0, places=6)


class TestInverseKinematics(unittest.TestCase):
    def setUp(self):
        self.iface = SO101Interface()

    def test_ik_recovers_known_joint_target(self):
        # Solve IK for a pose generated by known joint angles, starting from
        # a different guess, and confirm the solved pose matches the target.
        home_q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        target_q = [0.3, -0.4, 0.5, 0.2, -0.1, 0.0]

        target_pose = self.iface.kinematics.fk(target_q)
        solved_q = self.iface.kinematics.ik(home_q, target_pose)
        solved_pose = self.iface.kinematics.fk(solved_q)

        error = pin.log(solved_pose.inverse() * target_pose).vector
        self.assertLess(np.linalg.norm(error), 1e-3)

    def test_set_eef_pose_does_not_crash(self):
        # Regression check: this used to raise (joint-count mismatch feeding
        # fk/ik). Without hardware connected it should simply return False.
        T = self.iface.get_eef_pose()
        xyz = T[:3, 3]
        rpy = pin.rpy.matrixToRpy(T[:3, :3])
        target_pose = list(xyz) + list(rpy)

        result = self.iface.set_eef_pose(target_pose)
        self.assertFalse(result)  # no bus connected


if __name__ == "__main__":
    unittest.main()
